/*
Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String,
that is generated by deleting some character of a given string without changing its order.
Examples: 
https://www.geeksforgeeks.org/print-subsequences-string/

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
 */
import java.util.ArrayList;
import java.util.List;
public class stringSubsequences {
	 static List<String>list = new ArrayList<String>();
	public static void main(String[] args) {
		String str ="abc";
		getAllSubsequence(str,"");
		System.out.println(list);
	}
	private static void getAllSubsequence(String str, String solution) {
		if(str.length()==0) {
			list.add(solution);
			return;
		}
		getAllSubsequence(str.substring(1), solution+str.charAt(0));
		getAllSubsequence(str.substring(1), solution);
	}
}